intl_sales_5/config/routes.rb
IntlSales5::Application.routes.draw do

  root :to => 'welcome#index'
  resources :sessions, :only => [:create, :new]
  resources :welcome, :only => [:show]
  resources :users
  resources :projects
  resources :sales do
    resources :sale_histories
  end
  
  match '/sessions/destroy' => 'sessions#destroy', :as => 'logout'
  


  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

intl_sales_5/app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :projects
end

intl_sales_5/app/models/medium.rb
class Medium < ActiveRecord::Base
   attr_accessible :name
   belongs_to :sale
end

intl_sales_5/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :user_id, :title, :budget_size
  belongs_to :user
  has_many :sales
  has_and_belongs_to_many :genres
end

intl_sales_5/app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :bid, :ask, :close, :close_date
  belongs_to :project
  has_many :sale_histories
  has_many :territories
  has_many :media
end

intl_sales_5/app/models/sale_history.rb
class SaleHistory < ActiveRecord::Base
  
  belongs_to :sale
end

intl_sales_5/app/models/territory.rb
class Territory < ActiveRecord::Base
  attr_accessible :name
  belongs_to :sale
end

intl_sales_5/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :username, :password, :password_confirmation, :email, :category
  has_many :projects
  has_secure_password
  validates :username, :email, :presence => true
  validates :password, :presence => true, :on => :create
  validates :username, :email, :uniqueness => true
  validates :email, :format => { :with => /.*[@].*[\.].*/}
  validates :password, :length => { :in => 6..20 }, :on => :create

end

intl_sales_5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  include Authentication
  helper_method :current_user
    
end

intl_sales_5/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def show
    @project = Project.find(params[:id])
    render 'projects/index'
  end

end

intl_sales_5/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render 'users/login'
  end

  def create
    authenticate_user(params["user"])
    session[:id] = @user.id
    
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def out
    render :layout => false
  end


end

intl_sales_5/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = User.find(params[:id])
  end  

  def new
    @user = User.new
  end  

  def show
    @user = User.find(params[:id])
    render 'users/index'
  end  
  
  def create
    @user = User.new(params[:user])
    @user.save
    session[:id] = @user.id
    p '$$$$%%'
    p params
    p @user.id
    redirect_to user_path(@user)
  end

end

intl_sales_5/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def show
    @user = User.new
  end
  
end

intl_sales_5/app/helpers/application_helper.rb
module ApplicationHelper

  
end

intl_sales_5/app/views/layouts/_nav1.erb
<nav>
  <ul>
    <li><%= link_to_unless_current "Home", root_path %></li>
    <% unless current_user %>
    <li><%=link_to_unless_current "Signup", new_user_path %></li>
    <li><%= link_to_unless_current "Login", new_session_path %></li>
    <% end %>
    <% if current_user %>
    <li><%= link_to_unless_current "Welcome, #{current_user.username}!", user_path(current_user) %></li>
    <li><%= link_to_unless_current "Logout", logout_path %></li>
    <% end %>
  </ul>
</nav>

intl_sales_5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntlSales5</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/nav1' %>
<%= yield %>

</body>
</html>

intl_sales_5/app/views/projects/index.html.erb
<div>
  <h1><%= @project.title %></h1>
</div>
<div>
  <h3>Project details</h3>
</div>
<div>
<div>
  <ul>
    <li>Genres</li>
    <li>Budget</li>
    <li>Description</li>
  </ul>
</div>
  <ul>
    <li><%= @project.genres.map { |g| g.name }.join(', ') %></li>
    <li><%= @project.budget_size %></li>
    <li><%= @project.description %></li>
  </ul>
</div>
<div>
  <h3>Sales</h3>
</div>
  <ul>
    <li>Territories</li>
    <li>Media</li>
    <li>Bid</li>
    <li>Ask</li>
    <li>Close</li>
    <li>Close Date</li>
  </ul>
<div>
  <% @project.sales.each do |s| %>
  <ul>
    <li><%= s.territories.map {|t| t.name }.join(', ') %> </li>
    <li><%=s.media.map {|m| m.name }.join(', ') %></li>
    <li><%=s.bid %></li>
    <li><%=s.ask %></li>
    <li><%=s.close %></li>
    <li><%=s.close_date %></li>
  </ul>
  <% end %>
</div>
</div>

intl_sales_5/app/views/users/_nav2.html.erb
<ul>
  <li><%= link_to_unless_current "Add Projects", new_user_project_path %></li>
  <li><%=link_to_unless_current "Add Sales", new_user_project_sale_path %></li>
</ul>

intl_sales_5/app/views/users/index.html.erb
<div>
  <h1><%= @user.username %>'s Profile</h1>
</div>
<div>
  <h2>Latest Projects</h2>
  <ul>
  <% @user.projects.each do |p| %>
    <li><%= link_to p.title, project_path(p) %></a></li>
  <% end %>
  </ul>
</div>
<div>
  <h2>Latest Sales</h2>
</div>

intl_sales_5/app/views/users/login.html.erb
<div>
  <h1>Login</h1>
  <%= form_tag(sessions_path, :method => 'post') do %>
    <%= label_tag("user_usernam", "Username") %>
    <%= text_field_tag("user[username]") %>
    <%= label_tag("user_password", "Password") %>
    <%= password_field_tag("user[password]", 'Enter Password') %>
    <%= submit_tag("Log In") %>
  <% end %>
</div>

intl_sales_5/app/views/users/new.html.erb
<div>
  <h1>Sign up</h1>
  <%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, :placeholder => 'Enter Username' %>
    <%= f.label :email %>
    <%= f.text_field :email, :placeholder => 'Enter Email' %>
    <%= f.label :password %>
    <%= f.password_field :password, :placeholder => 'Create Password' %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :placeholder => 'Re-enter Password' %>
    <%= f.submit 'Create Account' %>
  <% end %>
</div>

intl_sales_5/app/views/welcome/index.html.erb
<h1>welcome to blaxbox</h1>